generator_model: gpt-4o-2024-11-20
# generator_model: gemini-2.0-flash
discriminator_model: gpt-4o-2024-11-20
# discriminator_model: gemini-2.0-flash
evaluator_model: gpt-4o-2024-11-20

# discriminator_model: "deepseek-r1
discussion_round: 2
gan_method: independent
# gan_method: advice_list
# gan_method: summary
