# gpt-4o-mini:
#   model_name: gpt-4o-mini-2024-07-18
#   beautiful_name: GPT-4o-Mini-2024-07-18
#   endpoints: null
#   api_type: openai

deepseek-r1:
  model_name: deepseek-ai/deepseek-r1
  beautiful_name: DeepSeek-r1
  endpoints:
    api_base: https://integrate.api.nvidia.com/v1
    api_key: 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
  api_type: openai